### PR TITLE
Added: DipDup tutorial

### PR DESCRIPTION
**Pull request by Wizard1209**
# What 💻

> DipDup is a software framework that helps web3 developers create selective indexers for decentralized applications.

We have written a guide on how to index zkSync data and build an API on top of it using the DipDup framework.

# Evidence 📷
evidence

### CODE REVIEW

**Comment by dmirgaleev** [comment]
Hey team! A review would be much appreciated!

**Comment by dutterbutter** [comment]
@Wizard1209 thanks for the guide! Can you please address the links and spelling errors and we can get this merged in.

**Comment by Wizard1209** [comment]
@dutterbutter I believe the links and spelling errors were not recognized correctly, I changed the link format, but in the spelling errors only the name of a tool wasn't recognized as a word. I also updated the branch to the current state. Please confirm everything is correct for merge

**Comment by dutterbutter** [comment]
@Wizard1209 looks like you just need to include "pipx" to the https://github.com/matter-labs/zksync-web-era-docs/blob/main/cspell-zksync.txt file

**Comment by Wizard1209** [comment]
@dutterbutter Now everything should be good

**Review by dutterbutter — APPROVED** [review]

**Pull request merged**
