### PR TITLE
Add announcement bar to docs

### PR DESCRIPTION
**Pull request by krofax**
Added announcement bar to docs.

### CODE REVIEW

**Comment by kailash-manasarovar** [comment]
@krofax are you able to produce the message whenever a user runs the translation module, rather than have it live all the time? Also, the language needs changing to:

-> Our Google translate plugin is fairly limited at the current time and may mistranslate some words.

**Comment by krofax** [comment]
> @krofax are you able to produce the message whenever a user runs the translation module, rather than have it live all the time? Also, the language needs changing to:
> 
> -> Our Google translate plugin is fairly limited at the current time and may mistranslate some words.

@kailash-manasarovar Do you mean, whenever the language translator is clicked that the announcement bar should pop up?

Okay, I'll update the language. Thanks.

**Comment by kailash-manasarovar** [comment]
> > @krofax are you able to produce the message whenever a user runs the translation module, rather than have it live all the time? Also, the language needs changing to:
> > -> Our Google translate plugin is fairly limited at the current time and may mistranslate some words.
> 
> @kailash-manasarovar Do you mean, whenever the language translator is clicked that the announcement bar should pop up?
> 
> Okay, I'll update the language. Thanks.

Yes, exactly that :)

**Comment by krofax** [comment]
> > > @krofax are you able to produce the message whenever a user runs the translation module, rather than have it live all the time? Also, the language needs changing to:
> > > -> Our Google translate plugin is fairly limited at the current time and may mistranslate some words.
> > 
> > 
> > @kailash-manasarovar Do you mean, whenever the language translator is clicked that the announcement bar should pop up?
> > Okay, I'll update the language. Thanks.
> 
> Yes, exactly that :)

 @kailash-manasarovar can you check again please?

**Comment by kailash-manasarovar** [comment]
Interesting, yes. I wonder about the purple? Is there a better color? Do we have a color scheme from marketing?

Also, maybe add an extra sentence: "Refresh screen to remove."

Also, there seems to be a gap between the top of the page and the header. Can you close it please?

Screenshot 2023-06-05 at 09 52 23

**Review by kailash-manasarovar — CHANGES_REQUESTED** [review]
Please check comment.

**Pull request closed without merging**
