### PR TITLE
Remove trailing commas in contributors

### PR DESCRIPTION
**Pull request by krofax**
Remove trailing commas in contributors

### CODE REVIEW

**Comment by kailash-manasarovar** [comment]
Hi @krofax I had a look at this and it looks like the only contributor is you, and no-one else, for all the docs.

**Comment by krofax** [comment]
> Hi @krofax I had a look at this and it looks like the only contributor is you, and no-one else, for all the docs.

Super weird, I'll look into it.

**Comment by kailash-manasarovar** [comment]
> Hi @krofax I had a look at this and it looks like the only contributor is you, and no-one else, for all the docs.

Apologies. I think this is default behavior with previews.

**Comment by kailash-manasarovar** [comment]
Hi @krofax I checked locally and there are no contributors showing at all.

**Review by kailash-manasarovar — APPROVED** [review]
eeek

**Pull request merged**
