### PR TITLE
Getting started with the Rust SDK

### PR DESCRIPTION
**Pull request by jpcenteno**
# What :computer: 

This PR introduces a Getting started tutorial for the [Rust SDK](https://github.com/lambdaclass/zksync-web3-rs/)

# Why :hand:

- Provide a beginners overview on how to get started with our Rust SDK.

# Evidence :camera:

# Notes :memo:

- [x] Finish draft
- [x] Perform self review after taking some fresh air
- [x] Check grammar and spelling
- [x] Proof-implement the code to make sure it runs as intended.

ℹ️ UPDATE: moved to https://github.com/matter-labs/zksync-web-era-docs/pull/697

### CODE REVIEW

**Comment by jpcenteno** [comment]
Why was `Deploy preview / build_and_preview (pull_request)` skipped?

**Comment by dutterbutter** [comment]
@jpcenteno can you update to the base branch please. The reason preview is skipped is due to this line in the workflow file: 
```
if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
```
checks if the pull request originates from the same repository (i.e., it's not a fork).

**Comment by jpcenteno** [comment]
> @jpcenteno can you update to the base branch please. The reason preview is skipped is due to this line in the workflow file:
> 
> ```
> if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
> ```
> 
> checks if the pull request originates from the same repository (i.e., it's not a fork).

I get it, but I don't have permissions to create a PR in the upstream repo.

**Comment by jpcenteno** [comment]
I fixed the fork problem. Had to reupload to https://github.com/matter-labs/zksync-web-era-docs/pull/697

**Pull request closed without merging**
