### PR TITLE
Minor improve of readability

### PR DESCRIPTION
**Pull request by Tim-PF**
Added a , so you can better read the text.

# What :computer: 
* First thing updated with this PR
* Second thing updated with this PR
* Third thing updated with this PR

# Why :hand:
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR

# Evidence :camera:
Include screenshots, screen recordings, or `console` output here demonstrating that your changes work as intended

# Notes :memo:
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

### CODE REVIEW

**Comment by Fixue** [comment]
#930, #929, #928, #927, #926, #925, #922, #919, #917 all are github farming unmeaningfull PRs.

This is airdrop farming, with a high chance of botting/automatisation, that make the work harder for real contributors, repos reviewers and injust to the user.

I would strongly recommand to close that type of PRs for the time being to contain the post-airdrop spam there's going to be due to some Twitter engagement bait post, to avoid proliferation, and doing the changes yourself if needed.

By rejecting those unmeaningful farming PRs, that newly found "github farm" strategy will be considerated ineffective and the spam will soon end, for the benefit of reviewers, devs, users and tech.

If you're doing that with no malicious intent, please consider doing more meaningful contributions.

**Comment by kadirchan** [comment]
@Fixue Here we are trying to fix the errors in the documentation. We want readers to have a better experience. You, on the other hand, are talking trash about me without contributing anything from your 4 day old Github which probably for "farming".  Nothing is promised here. Don't make ridiculous comments about people without looking at the commits. smart*ss

**Comment by Fixue** [comment]
@kardirchan No you're not, you're a github farming 

https://github.com/matter-labs/awesome-zero-knowledge-proofs/pull/83

Keep doing unmeaningfull PRs and spamming the reviewers, you'll get nothing

**Comment by Tim-PF** [comment]
I just saw something to improve. I dont need to be rewarded for improving readibility. I never expected that such a minor contribution will even be considered for rewards. My github is older than 1 year and active almost daily.
I study CS and never heard of anyone in this space being bothered by helping to improve readibility in the docs.
Your accusations are hurtful @Fixue . You never coded a single day in your life yet you try to make others who try to help look bad.

**Comment by devwankel** [comment]
Hey @Fixue, they will reward you for getting this under control bro. That's what "Contributors" is for. If there is a bug to merge, that is done. It goes on until there's nothing left to merge. You know what? Just STFU

**Comment by kadirchan** [comment]
Hey @Fixue just STFU
We call open source to this unmeaningfull PRs
and you can cry

**Comment by Fixue** [comment]
The github farmers are fighting back!

"I study CS and never heard of anyone in this space being bothered by helping to improve readibility in the docs." and it's just a completly useless PRs that adds a coma, good spam you got there mate

Rage all you want, you won't get anything from that and all your useless PRs will get closed.

Saved all you guys profile, I'll be there on all of your github farming PRs to make sure none of them ever get merged.

Or you can simply start doing real contribution and stop spamming, then I'll indeed shut it, but a coma won't do it farmers.

Stay mad

**Comment by Tim-PF** [comment]
> The github farmers are fighting back!
> 
> "My github is older than 1 year and active almost daily."
> 
> But it's your first ever PR that happened right after the Starknet airdrop on an anticipated project, such a coincidence !
> 
> "I study CS and never heard of anyone in this space being bothered by helping to improve readibility in the docs." and it's just a completly useless PRs that adds a coma, good spam you got there mate
> 
> Rage all you want, you won't get anything from that and all your useless PRs will get closed.
> 
> Saved all of you guys profiles, I'll be there on every single one of your github farming PRs to make sure none of them ever get merged.
> 
> Or you can simply start doing real contribution and stop spamming, then I'll indeed shut it, but a coma won't do it farmers.
> 
> Stay mad & keep wasting time or stop the farming and start contributing for real, it's up to you liars

I dont even know what Starknet is. I am interested in ZK not every Crypto Project out there!
Also this is my private Github mostly for learning. On my work Github I got more than this one. I did not even notice this is my first on this account. In addition nobody needs to justify themself just because you want to play Police stop threatening random users who do nothing but good.
I have to block you because you seem paranoid. Get some help mate!

**Comment by devwankel** [comment]
@Fixue Don't worry, Everything's under control. There are literate guys working at Matter Labs and they know which PRs to merge. Zksync encourages developers to github and asks them to contribute. They're aware of everything. You don't need to advise anyone.

**Comment by arose0** [comment]
Closing per https://github.com/matter-labs/zksync-era/blob/main/CONTRIBUTING.md#faq

Additionally, this sentence is meant to read "elevate test quality" and "elevate, test quality" doesn't make sense here.

**Pull request closed without merging**
