### PR TITLE
Add documentation for the hardhat-zksync-node plugin

### PR DESCRIPTION
**Pull request by mpopovac-txfusion**
# What :computer: 
* Added documentation for the hardhat-zksync-node plugin
* Provided installation steps for @matterlabs/hardhat-zksync-node
* Detailed configuration and commands associated with the plugin

# Why :hand:
* To guide users on how to integrate and use the hardhat-zksync-node plugin with hardhat
* To provide clarity on installation methods using both yarn and npm
* To list and explain available commands, their options, and respective functionalities

# Evidence :camera:
image

### CODE REVIEW

**Review by idea404 — DISMISSED** [review]
LGTM. 

I would add here also how adding this dep will allow tests to run against it without additional configuration, with the plugins handling the setup and shutdown of the node before and after tests. Let's see how the plugin integration goes first before proceeding with adding that content here though.

**Review by idea404 — DISMISSED** [review]

**Review by idea404 — DISMISSED** [review]

**Comment by JackHamer09** [comment]
> By invoking the test task with the Hardhat network's zksync flag set to true, the plugin initiates an In-memory node alongside the tests

That didn't work for me.

hardhat.config.ts
```ts
import { HardhatUserConfig } from "hardhat/config";

import "@matterlabs/hardhat-zksync-node";
import "@matterlabs/hardhat-zksync-deploy";
import "@matterlabs/hardhat-zksync-solc";
import "@matterlabs/hardhat-zksync-verify";

const config: HardhatUserConfig = {
  networks: {
    zkSyncEraTestnet: {
      url: "https://testnet.era.zksync.dev",
      ethNetwork: "goerli",
      zksync: true,
      verifyURL: "https://zksync2-testnet-explorer.zksync.dev/contract_verification",
    },
    hardhat: {
      zksync: true,
    },
  },
  zksolc: {
    version: "latest",
    settings: {},
  },
  solidity: {
    version: "0.8.17",
  },
};

export default config;
```

```bash
yarn hardhat test
```

Error:
```
> Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":55,\"error\":{\"code\":-32000,\"message\":\"transaction type not supported\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x71f9131006843b9aca07843b9aca0782577894000000000000000000000000000000000000800680b8e49c4d535b00000000000000000000000000000000000000000000000000000000000000000100008d819c2839235646c4e84cb40f6159ceebdc241b3518420a975369e96400000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000024869000000000000000000000000000000000000000000000000000000000000098080099436615cf349d7f6344891b1e7ca7c72883f5dc04982c350f911a3b911a000020000000000020005000000000002000100000001035500000000030100190000006003300270000000820030019d0000008004000039000000400040043f00000082033001970000000102200190000000a80000c13d000000040230008c000001880000413d000000000101043b000000e001100270000000870210009c000001770000613d000000880110009c000001880000c13d0000000001000416000000000101004b000001880000c13d0000000003000031000000040130008a0000008402000041000000200410008c000000000400001900000000040240190000008401100197000000000501004b000000000200a019000000840110009c00000000010400190000000001026019000000000101004b000001880000c13d00000001040003670000000401400370000000000501043b000000830150009c000001880000213d00000023015000390000008402000041000000000631004b0000000006000019000000000602801900000084073001970000008401100197000000000871004b0000000002008019000000000171013f000000840110009c00000000010600190000000001026019000000000101004b000001880000c13d0000000406500039000000000164034f000000000101043b000000830210009c000001da0000213d000000bf07100039000000200200008a000000000727016f000000830870009c000001da0000213d000000400070043f000000800010043f00000000051500190000002405500039000000000335004b000001880000213d0000002003600039000000000334034f0000001f0410018f0000000505100272000000560000613d00000000060000190000000507600210000000000873034f000000000808043b000000a00770003900000000008704350000000106600039000000000756004b0000004e0000413d000000000604004b000000650000613d0000000505500210000000000353034f0000000304400210000000a005500039000000000605043300000000064601cf000000000646022f000000000303043b0000010004400089000000000343022f00000000034301cf000000000363019f0000000000350435000000a0011000390000000000010435000000800100043d000000830310009c000001da0000213d000000000400041a000000010340019000000001034002700000007f0530018f00000000030560190000001f0530008c00000000050000190000000105002039000000000454013f0000000104400190000001960000c13d000000200430008c000000870000413d0000001f04100039000000050440027000000089044000410000008905000041000000200610008c000000000405401900000000000004350000001f0330003900000005033002700000008903300041000000000534004b000000870000813d000000000004041b0000000104400039000000000534004b000000830000413d0000001f0310008c000001f10000a13d0000000003210170000000a004000039000000890200004100000000000004350000009b0000613d000000890200004100000020060000390000000004000019000000000506001900000080065000390000000006060433000000000062041b000000200650003900000001022000390000002004400039000000000734004b000000910000413d000000a004500039000000000313004b000000a50000813d0000000303100210000000f80330018f000000010500008a000000000335022f000000000353013f0000000004040433000000000334016f000000000032041b00000001020000390000000103100210000001fb0000013d0000000001000416000000000101004b000001880000c13d00000000010000310000001f02100039000000200900008a000000000492016f000000400200043d0000000003240019000000000443004b00000000040000190000000104004039000000830530009c000001da0000213d0000000104400190000001da0000c13d000000400030043f0000001f0310018f00000001040003670000000505100272000000c60000613d000000000600001900000005076002100000000008720019000000000774034f000000000707043b00000000007804350000000106600039000000000756004b000000be0000413d000000000603004b000000d50000613d0000000505500210000000000454034f00000000055200190000000303300210000000000605043300000000063601cf000000000636022f000000000404043b0000010003300089000000000434022f00000000033401cf000000000363019f00000000003504350000008403000041000000200410008c000000000400001900000000040340190000008405100197000000000605004b000000000300a019000000840550009c000000000304c019000000000303004b000001880000c13d0000000004020433000000830340009c000001880000213d000000000312001900000000012400190000001f021000390000008404000041000000000532004b0000000005000019000000000504801900000084022001970000008406300197000000000762004b0000000004008019000000000262013f000000840220009c00000000020500190000000002046019000000000202004b000001880000c13d0000000002010433000000830420009c000001da0000213d0000003f04200039000000000494016f000000400700043d0000000004470019000000000574004b00000000050000190000000105004039000000830640009c000001da0000213d0000000105500190000001da0000c13d000000400040043f000000000627043600000000042100190000002004400039000000000334004b000001880000213d000000000302004b000001120000613d000000000300001900000000046300190000002003300039000000000513001900000000050504330000000000540435000000000423004b0000010b0000413d000000000126001900000000000104350000000004070433000000830140009c000001da0000213d000000000100041a000000010210019000000001011002700000007f0310018f000000000301c0190000001f0130008c00000000010000190000000101002039000000010110018f000000000112004b000001960000c13d000000200130008c000001480000413d000100000003001d000300000004001d000000000000043500000082010000410000000002000414000000820320009c0000000001024019000000c00110021000000085011001c70000801002000039000500000009001d000400000007001d000200000006001d020401ff0000040f0000000206000029000000040700002900000005090000290000000102200190000001880000613d00000003040000290000001f024000390000000502200270000000200340008c0000000002004019000000000301043b00000001010000290000001f01100039000000050110027000000000011300190000000002230019000000000312004b000001480000813d000000000002041b0000000102200039000000000312004b000001440000413d0000001f0140008c000001e00000a13d000300000004001d000000000000043500000082010000410000000002000414000000820320009c0000000001024019000000c00110021000000085011001c70000801002000039000500000009001d000400000007001d020401ff0000040f000000040600002900000005030000290000000102200190000001880000613d000000030700002900000000033701700000002002000039000000000101043b000001690000613d0000002002000039000000000400001900000000056200190000000005050433000000000051041b000000200220003900000001011000390000002004400039000000000534004b000001610000413d000000000373004b000001740000813d0000000303700210000000f80330018f000000010400008a000000000334022f000000000343013f00000000026200190000000002020433000000000232016f000000000021041b00000001010000390000000102700210000001ea0000013d0000000001000416000000000101004b000001880000c13d000000040100008a00000000011000310000008402000041000000000301004b000000000300001900000000030240190000008401100197000000000401004b000000000200a019000000840110009c00000000010300190000000001026019000000000101004b0000018a0000613d00000000010000190000020600010430000000000400041a000000010540019000000001014002700000007f0210018f000000000301001900000000030260190000001f0130008c00000000010000190000000101002039000000000114013f00000001011001900000019a0000613d0000008a0100004100000000001004350000002201000039000001dd0000013d000000400200043d0000000001320436000000000505004b000001ac0000613d0000000000000435000000000403004b0000000004000019000001b20000613d000000890500004100000000040000190000000006410019000000000705041a000000000076043500000001055000390000002004400039000000000634004b000001a40000413d000001b20000013d000001000500008a000000000454016f0000000000410435000000000303004b000000200400003900000000040060190000003f03400039000000200400008a000000000543016f0000000003250019000000000553004b00000000050000190000000105004039000000830630009c000001da0000213d0000000105500190000001da0000c13d000000400030043f00000020050000390000000005530436000000000202043300000000002504350000004005300039000000000602004b000001cd0000613d000000000600001900000000075600190000000008610019000000000808043300000000008704350000002006600039000000000726004b000001c60000413d000000000125001900000000000104350000005f01200039000000000141016f0000008202000041000000820410009c0000000001028019000000820430009c000000000203401900000040022002100000006001100210000000000121019f000002050001042e0000008a0100004100000000001004350000004101000039000000040010043f0000008b010000410000020600010430000000000104004b0000000001000019000001e40000613d00000000010604330000000302400210000000010300008a000000000223022f000000000232013f000000000221016f0000000101400210000000000112019f000000000010041b0000002001000039000001000010044300000120000004430000008601000041000002050001042e000000000201004b0000000002000019000001f50000613d000000a00200043d0000000303100210000000010400008a000000000334022f000000000343013f000000000332016f0000000102100210000000000123019f000000000010041b0000000001000019000002050001042e00000202002104230000000102000039000000000001042d0000000002000019000000000001042d0000020400000432000002050001042e0000020600010430000000000000000000000000000000000000000000000000000000000000000000000000ffffffff000000000000000000000000000000000000000000000000ffffffffffffffff80000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000020000000000000000000000000000000020000000000000000000000000000004000000100000000000000000000000000000000000000000000000000000000000000000000000000cfae321700000000000000000000000000000000000000000000000000000000a4136862290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e5634e487b71000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024000000000000000000000000333c061611114a8c1e55e13055449aae679e565ce7350d1b3b894d0d07afdbc1b84169587dec18360beaecd24456e5dca381b3b167b27b58016db55a33738c3421905d783b0b7828ac450a9a03b1c66b8672cc6df2da4485c8fc096027da5b959ad21bc0\"],\"id\":55,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8545", code=SERVER_ERROR, version=web/5.7.1)
```

**Comment by MexicanAce** [comment]
@JackHamer09 Can you link to the tests that are using your hardhat config? Strange that it's trying to reach Port `8545`.

@mpopovac-txfusion Thoughts?

**Comment by JackHamer09** [comment]
I wonder why it's not even just failing with a network error, but fails with `transaction type not supported` for basic greeter deployment.

**Comment by mpopovac-txfusion** [comment]
I would like to note two things here:

- There is no network set with the URL "http://localhost:8545/" in the hardhat.config file. This means that, in tests, you are using a provider that is instantiated with this URL. Additionally, this port (8545) is often used by the geth (L1) container run from a local setup. This suggests that you are sending requests to L1 and not to the zkSync network, which might explain the unusual error you're encountering. My assumption here is that you haven't instantiated a provider as explained in the documentation, and you're using a deployer with default configurations in your tests.
- The node is operational since you are receiving requests from it (regardless of the error). When the node isn't running, the typical response is something like "noNetwork."

This is merely an assumption based on the file and the error you provided. If you still encounter the same issue, please follow @MexicanAce advice and send us the tests. Better yet, share the link to the repository.

**Comment by JackHamer09** [comment]
> I just saw your answers. The issue arrises in this line: `const provider = new Provider(zkSyncTestnet.url);`.

Ah, I actually did some changes locally and I already use `hre.network.config.url`

**Comment by mpopovac-txfusion** [comment]
> > I just saw your answers. The issue arrises in this line: `const provider = new Provider(zkSyncTestnet.url);`.
> 
> Ah, I actually did some changes locally and I already use `hre.network.config.url`

I just pulled that example template, made only that one change I recommended, and run tests successfuly. Can you send a link to the repo so I can see what you changed?

**Comment by JackHamer09** [comment]
@mpopovac-txfusion Here are the changes I've made: https://github.com/matter-labs/zksync-hardhat-template/pull/11

According to the tutorial I've added `import "@matterlabs/hardhat-zksync-node"` and `hardhat: {zksync: true}`

Is there anything else I've missed? Also against which network should the tests be running? Or feel free to just add comments in the linked PR. Thank you!

**Comment by JackHamer09** [comment]
Btw to make sure we're on the same page:
I expect to not start era-test-node manually and expect it to start automatically when I start the tests, according to the documentation:
> ... the plugin initiates an In-memory node alongside the tests ...

**Comment by mpopovac-txfusion** [comment]
> Btw to make sure we're on the same page: I expect to not start era-test-node manually and expect it to start automatically when I start the tests, according to the documentation:
> 
> > ... the plugin initiates an In-memory node alongside the tests ...
> 
> However I don't see logs about anything being started in the console and just see the tests failing. It fails with NO_NETWORK now. Might be related to the fact that I had local-setup started in background and I guess it uses localhost:8545 as default rpcUrl.

The purpose of the plugin is to run everything automatically like you explained. I think I've found an issue, you are using the first version of the `hardhat-zksync-node` plugin when only the running node from the hardhat was enabled. Please use latest version `0.0.1-beta.4`. Let me know if this fixed your problem.

**Comment by JackHamer09** [comment]
It works now, thank you!
Should documentation also mention that tests should be run against `hardhat` network (eg. `hardhat test --network hardhat`). Cause if different `defaultNetwork` is specified then it won't use correct network.

**Comment by mpopovac-txfusion** [comment]
> It works now, thank you!
> Should documentation also mention that tests should be run against `hardhat` network (eg. `hardhat test --network hardhat`)? Cause if different `defaultNetwork` is specified then it won't use correct network.

No problem! 
I assumed this was clear from the documentation, but since you asked, it probably indicates that it needs to be clearer. Thank you; I will work on making it more explicit.

**Comment by idea404** [comment]
@mpopovac-txfusion could you please resolve conflicts and update the branch? Just ping me then and happy to approve

**Review by idea404 — APPROVED** [review]

**Pull request merged**
